### ISSUE TITLE
Allowed HTTP Origin doesn't work with ipfs-copy

### ISSUE THREAD

**Issue by casualuser** [INFURA/ipfs-copy#4]
we're trying to migrate to infura ipfs with this tool but faced with unclear issue
please help to investigate and fix

```
[ec2-user@ip-10-0-33-62 ~]$ ipfs --version
ipfs version 0.4.22
[ec2-user@ip-10-0-33-62 ~]$ sudo netstat -nlp | grep 5001
tcp        0      0 0.0.0.0:5001            0.0.0.0:*               LISTEN      22287/ipfs
[ec2-user@ip-10-0-33-62 ~]$ ipfs-copy --source-api-url=http://localhost:5001 --project-id=my_id --project-secret=my_secret
2021/07/15 07:26:02 [ERROR] version: not allowed - invalid origin
```

**Comment by casualuser** [comment]
@EnchanterIO 
I guess that we're hitting error in this part of code 
https://github.com/INFURA/ipfs-copy/blob/master/cmd/ipfs-copy/main.go#L44-L48

what may be the real reason of this? can you check logs from infura side?

**Comment by casualuser** [comment]
from code I can see the same
https://monosnap.com/file/lJjpb4TbihLRscgaKit06gI8y0PLMU

so it looks like there is something at another side

**Comment by EnchanterIO** [comment]
Hey @casualuser, thanks for reporting. Investigating now and will get back to you.

**Comment by EnchanterIO** [comment]
Hi @casualuser , there seems to be two issues. One on ipfs-copy side and one on your source IPFS node.

You are using an older IPFS version from 2019 which didn't have a stream support for `pin/ls` operation. I created a PR to make it possible for you to use ipfs-copy without any changes on your side. Once the, above linked, PR is merged and new ipfs-copy binary is built, you can retry the process and it should work now. I tested specifically with your 0.4.22 version. Thanks for providing that info.

The error about `version: not allowed - invalid origin`, seems to be a CORS issue. Check your IPFS config and the API section, maybe you have restricted access from localhost?

See this SO issue with more details how to reconfigure it: https://stackoverflow.com/a/66832303/1162217

The default config looks like this:
![Screenshot from 2021-07-21 11-48-30](https://user-images.githubusercontent.com/3595242/126469345-9ced2720-1333-49e1-94b9-e4591825be66.png)

**Comment by EnchanterIO** [comment]
@casualuser, the new `ipfs-copy` version is ready. You can download it from: https://github.com/INFURA/ipfs-copy/releases/tag/v1.1.0

**Comment by casualuser** [comment]
@EnchanterIO we have tried with new version but still question with CORS persists and it looks like at Infura side.
please check e-mail forwarded from Michael and help us test new version

**Comment by EnchanterIO** [comment]
Hi @casualuser,

I reviewed the email. Let's do 2 more things to debug this.

## To debug your connection with Infura (the migration destination node)
### Validate you can access Infura API - general request without credentials
```
curl -X POST "https://ipfs.infura.io:5001/api/v0/cat?arg=QmeGAVddnBSnKc1DLE7DLV9uuTqo5F7QbaveTjr45JUdQn"
```
> Infura IPFS - Getting started demo.

This part must work.

### Validate your Infura account has no security settings limitations - with credentials
```
curl -X POST -u "PROJECT_ID:PROJECT_SECRET" "https://ipfs.infura.io:5001/api/v0
/cat?arg=QmeGAVddnBSnKc1DLE7DLV9uuTqo5F7QbaveTjr45JUdQn"
```
> Infura IPFS - Getting started demo.

If you get an `invalid-origin` error using credentials then go to your project's security settings page and make sure it's configured to be reachable from where you run it. The default settings for your account should be reachable from everywhere:

![Screenshot from 2021-07-30 10-49-07](https://user-images.githubusercontent.com/3595242/127627748-3804b22b-6bfd-47e4-a40a-ea64827295fd.png)

This is the place you have to configure your allowed origins.


PS: you can write me directly on [LinkedIn](https://www.linkedin.com/in/llukac/) for real-time conversation to speed things up.

**Comment by casualuser** [comment]
@EnchanterIO 

I should say that it looks like `allowlists` settings do not work properly because if I'm adding my public ip address in `ALLOWED HTTP ORIGINS ` then previous error with `not allowed - invalid origin` immediately appear

Anyway I've tried to reach you via Linkedin messages to invite to our slack but still haven't received any answers there.

So posting some tech logs here because access to Linkedin for me limited from my location and you still not in our shared Slack channel.

```
[ec2-user@ip-10-0-33-62 ~]$ /usr/local/bin/ipfs-copy --source-api-url=http://localhost:5001 --project-id=123 --project-secret=890
2021/08/03 08:53:48 [INFO] Infura IPFS version is: 0.7.0
2021/08/03 08:53:48 [INFO] Pinning CIDs to https://ipfs.infura.io:5001 with 5 workers...
 0 / ? [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------=]2021/08/03 08:53:48 [INFO] Source IPFS version is: 0.4.22
2021/08/03 08:53:48 [DEBUG] Source IPFS pin/ls --stream support?: false
 42s  0 / ? [----------------------------------------------------------------------------------------------------------------------------------------------------------------------=]^C
```

```
[ec2-user@ip-10-0-33-62 ~]$ /usr/local/bin/ipfs-copy --cids=./pin_rec.txt --project-id=123 --project-secret=890
2021/08/03 08:51:29 [INFO] Infura IPFS version is: 0.7.0
2021/08/03 08:51:29 [INFO] Pinning CIDs to https://ipfs.infura.io:5001 with 5 workers...
2021/08/03 08:52:29 [ERROR] Failed pinning CID 'Qma11myhqqPasKyGDWnjp3RNdoEcGBejyvMCgjAfeqKoB6'. pin/add: Gateway Timeout
2021/08/03 08:52:29 [ERROR] Failed pinning CID 'Qma113CPsXoxT4RNxpbAN7t28Bck2M4NKVLzBfQzgA9y81'. pin/add: Gateway Timeout
2021/08/03 08:52:29 [ERROR] Failed pinning CID 'Qma113voXhWn8QwBZoFihi61Lpsu9XGvuFnzG7Lp2vd84j'. pin/add: Gateway Timeout
2021/08/03 08:52:29 [ERROR] Failed pinning CID 'Qma11Ka6zVcaL2jqz1X5zv34VTZhapzgWrPLRk7eWzbCUq'. pin/add: Gateway Timeout
2021/08/03 08:52:29 [ERROR] Failed pinning CID 'Qma11mrsMt6axM6yMYMJgydCQJGr8EwLbFkJPHS9tcExwR'. pin/add: Gateway Timeout
2021/08/03 08:53:29 [ERROR] Failed pinning CID 'Qma11Rm7tJPJPH95MZeYEyPhV8GN7LAvZzNCpt5PtpQkNC'. pin/add: Gateway Timeout
2021/08/03 08:53:29 [ERROR] Failed pinning CID 'Qma11rvaf4S8iUEBXoEMz997ry135dRek4yyTemGHk6FUb'. pin/add: Gateway Timeout
2021/08/03 08:53:29 [ERROR] Failed pinning CID 'Qma11VKmp8oGzS75CHXM3Nqvei63zGoHvP1fVLSGdixvPQ'. pin/add: Gateway Timeout
2021/08/03 08:53:29 [ERROR] Failed pinning CID 'Qma11VYRx7ygTSW1LfYwPpqb52teQS2TwqW9K1mPa4AAGs'. pin/add: Gateway Timeout
2021/08/03 08:53:29 [ERROR] Failed pinning CID 'Qma11TUcDNUq5KPdC6RgNkg7nk8KBKSSNzX7YoHaK75H1n'. pin/add: Gateway Timeout
```

But access with creds works now:
```
[ec2-user@ip-10-0-33-62 ~]$ curl -X POST -u "123:890" "https://ipfs.infura.io:5001/api/v0/cat?arg=QmeGAVddnBSnKc1DLE7DLV9uuTqo5F7QbaveTjr45JUdQn"
Infura IPFS - Getting started demo.
```

Please advise and it will be nice if you will join Slack with my link from Linkedin.

**Comment by EnchanterIO** [comment]
As we discussed on Slack:

> `ipfs-copy` as migration tool, isn't adding the Origin header comparing to Browsers or other clients. But once you migrate your content, and start working on a DApp or something running in a Browser or a different client generating all the headers then u can secure it either by domain or IP.

**To limit access to your project when running `ipfs-copy` specify your IP in the `Limit IP Access` of your project's settings**.

Example:
![Screenshot from 2021-08-06 14-00-23](https://user-images.githubusercontent.com/3595242/128507378-fcbd06a3-d1a6-4663-b2e2-66555dd88030.png)

The `ipfs-copy` will throw this error:
> 2021/08/06 14:00:11 [ERROR] version: not allowed - invalid ip

I updated the Readme docs and also documented the usage of: `--workers` and `--cids-failed` flags for more info.
