### ISSUE TITLE
ipfs-copy.exe not installing anything

### ISSUE THREAD

**Issue by christopheSeeka** [INFURA/ipfs-copy#7]
Hello, i downloaded ipfs-copy-v1.2.0-windows-386, i’m on windows 10 but when i double click on it, nothing happen and it install nothing so running ipfs-copy in bash give the expected command not found.

Any idea why? I tried it a couple of month ago, on another computer and it was working, did anything change? I don’t have any firewall or antivirus on and i can execute any other .exe.

**Comment by MichaelMure** [comment]
For the command to work in the terminal, you will need to install the .exe in one of your PATH folder, where the terminal is looking for program.

You can see where those folders are with the command `echo %path%` in the windows terminal.

**Comment by christopheSeeka** [comment]
Thank you, Adding a new windows environment variable pointing to it work. I don't recall having to do that before but it works so I guess I did when tried it few months ago :)
